### ISSUE TITLE
The applied trait message displays incorrectly on 1.15.2-1.1.1.jar

### ISSUE THREAD

**Issue by JMZED** [Zorochase/NeoArsenal#2]
The message that displays when you add a trait to any tool displays incorrectly.
For example, applying efficiency on an axe displays: "neoarsenal.lore.applied_traitEfficient"
Image: https://imgur.com/a/2xukyi1

**Comment by Zorochase** [comment]
Can't believe I didn't catch this -_-
I've replaced the file on Curseforge with a fixed version (same goes for 1.14).

Thanks for reporting.
