### ISSUE TITLE
Enchantments from other mods can be applied using enchanting table but not anvil on 1.15.2-1.1.1.jar

### ISSUE THREAD

**Issue by JMZED** [Zorochase/NeoArsenal#3]
Enchantments from other mods (specifically Ensorcellation: https://www.curseforge.com/minecraft/mc-mods/ensorcellation) can be applied to NeoArsenal's tools using an enchanting table. I enchanted quite a few items and was never able to get vanilla enchantments but would get 1-3 of Ensorcellation's enchantments. I also tried to apply both vanilla and modded enchantments onto NeoArsenal's tools using an anvil but this does not work (as intended).

Is this something that would need cross compatibility with other mods or is there some way to completely remove NeoArsenal's tools from the enchantability list?

**Comment by Zorochase** [comment]
I thought returning false in canApplyAtEnchantingTable would be enough to prevent that, but apparently it wasn't. I have plans for dealing with enchantments for other mods, but for now I've released another fix that stops them from being applied at the table.
